version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: id1
    binary: dtdiff
    dir: ./cmd/dtdiff
    ldflags:
      - -extldflags "-static" -s -w -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -X main.Version={{.Version}} -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - ppc64le
    goarm:
      - "7"
    ignore:
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: ppc64le
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: ppc64le

  - id: id2
    binary: dtdiff
    dir: ./cmd/dtdiff
    ldflags:
      - -extldflags "-static" -s -w -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -X main.Version={{.Version}} -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    hooks:
      post:
        - upx -9 "{{ .Path }}"

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.xz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}--checksums.txt"
release:
  draft: false
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: dtdiff
    repository:
      owner: jftuga
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TOKEN }}"
    commit_author:
      name: jftuga
      email: jftuga@users.noreply.github.com
    homepage: https://github.com/jftuga/dtdiff
    description: "dtdiff: output the difference between date, time or duration"
    test: system "#{bin}/dtdiff -v"
    install: bin.install "dtdiff"
